cat << EOF > /root/helm-tomcat.yml
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
      app: {{ .Values.app }} 
  name: {{ .Release.Name }}-deployment
spec: 
  replicas: {{ .Values.Replicas }}
  selector: 
    matchLabels: 
      app: {{ .Values.app }}
  template: 
    metadata: 
      labels: 
        app: {{ .Values.app }}
    spec: 
      containers: 
        - image: {{ .Values.image_name }}:{{ .Values.tag_name }} 
          name: {{ .Values.Container_name }}

---      
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      nodePort: {{ .Values.nodeport }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.target_port }}
EOF      
